// flow-typed signature: 413d6bf7aaf039faaebe8b46d118d962
// flow-typed version: <<STUB>>/react-handsontable_v0.3.1/flow_v0.52.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-handsontable'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-handsontable' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-handsontable/dist/react-handsontable' {
  declare module.exports: any;
}

declare module 'react-handsontable/dist/react-handsontable.min' {
  declare module.exports: any;
}

declare module 'react-handsontable/src/index' {
  declare module.exports: any;
}

declare module 'react-handsontable/src/react-handsontable' {
  declare module.exports: any;
}

declare module 'react-handsontable/src/settingsMapper' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-handsontable/dist/react-handsontable.js' {
  declare module.exports: $Exports<'react-handsontable/dist/react-handsontable'>;
}
declare module 'react-handsontable/dist/react-handsontable.min.js' {
  declare module.exports: $Exports<'react-handsontable/dist/react-handsontable.min'>;
}
declare module 'react-handsontable/src/index.js' {
  declare module.exports: $Exports<'react-handsontable/src/index'>;
}
declare module 'react-handsontable/src/react-handsontable.jsx' {
  declare module.exports: $Exports<'react-handsontable/src/react-handsontable'>;
}
declare module 'react-handsontable/src/settingsMapper.js' {
  declare module.exports: $Exports<'react-handsontable/src/settingsMapper'>;
}
