// flow-typed signature: ac4e0df0198cf1779f9d6231f0d1db78
// flow-typed version: <<STUB>>/@handsontable/react_v2.0.0/flow_v0.84.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@handsontable/react'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@handsontable/react' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@handsontable/react/commonjs/react-handsontable' {
  declare module.exports: any;
}

declare module '@handsontable/react/dist/react-handsontable' {
  declare module.exports: any;
}

declare module '@handsontable/react/dist/react-handsontable.min' {
  declare module.exports: any;
}

declare module '@handsontable/react/es/react-handsontable' {
  declare module.exports: any;
}

// Filename aliases
declare module '@handsontable/react/commonjs/react-handsontable.js' {
  declare module.exports: $Exports<'@handsontable/react/commonjs/react-handsontable'>;
}
declare module '@handsontable/react/dist/react-handsontable.js' {
  declare module.exports: $Exports<'@handsontable/react/dist/react-handsontable'>;
}
declare module '@handsontable/react/dist/react-handsontable.min.js' {
  declare module.exports: $Exports<'@handsontable/react/dist/react-handsontable.min'>;
}
declare module '@handsontable/react/es/react-handsontable.js' {
  declare module.exports: $Exports<'@handsontable/react/es/react-handsontable'>;
}
